INSERT INTO ITEMS (NAME, DESCRIPTION) VALUES ('item_1', 'item_1');
INSERT INTO ITEMS (NAME, DESCRIPTION) VALUES ('item_2', 'item_2');
INSERT INTO ITEMS (NAME, DESCRIPTION) VALUES ('item_3', 'item_3');
INSERT INTO ITEMS (NAME, DESCRIPTION) VALUES ('item_4', 'item_4');
INSERT INTO ITEMS (NAME, DESCRIPTION) VALUES ('item_5', 'item_5');
INSERT INTO ITEMS (NAME, DESCRIPTION) VALUES ('item_6', 'item_6');